// Generated by CoffeeScript 1.9.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET home page. */

  module.exports = {
    index: function(req, res) {
      return res.render('index', {
        title: 'Predictive parser'
      });
    }
  };

}).call(this);
